"""Skill taxonomy: canonical skills, display names, aliases, and categories.

The taxonomy is the single source of truth for what counts as a "skill".
Every alias (including the canonical key itself) maps to one canonical form,
so "K8s", "kubernetes" and "Kubernetes" all resolve to the same skill.

Structure of _TAXONOMY_SOURCE:
    { category: { canonical_key: (display_name, (alias, ...)) } }

Canonical keys and aliases are lowercase. Matching patterns are generated
from both in `skills.py`.
"""

from __future__ import annotations

_TAXONOMY_SOURCE: dict[str, dict[str, tuple[str, tuple[str, ...]]]] = {
    "Programming Languages": {
        "python": ("Python", ()),
        "java": ("Java", ()),
        "javascript": ("JavaScript", ("java script",)),
        "typescript": ("TypeScript", ("type script",)),
        "c++": ("C++", ("cpp", "c plus plus")),
        "c#": ("C#", ("c sharp", "csharp")),
        "c": ("C", ()),
        "go": ("Go", ("golang",)),
        "rust": ("Rust", ()),
        "ruby": ("Ruby", ()),
        "php": ("PHP", ()),
        "swift": ("Swift", ()),
        "kotlin": ("Kotlin", ()),
        "scala": ("Scala", ()),
        "r": ("R", ("rstudio",)),
        "matlab": ("MATLAB", ()),
        "perl": ("Perl", ()),
        "julia": ("Julia", ()),
        "dart": ("Dart", ()),
        "elixir": ("Elixir", ()),
        "haskell": ("Haskell", ()),
        "lua": ("Lua", ()),
        "objective-c": ("Objective-C", ("objective c", "objc")),
        "groovy": ("Groovy", ()),
        "fortran": ("Fortran", ()),
        "cobol": ("COBOL", ()),
        "assembly": ("Assembly", ("assembly language", "asm")),
        "solidity": ("Solidity", ()),
        "bash": ("Bash", ()),
        "shell scripting": ("Shell scripting", ("shell script", "shell scripts")),
        "powershell": ("PowerShell", ("power shell",)),
        "vba": ("VBA", ("visual basic for applications", "visual basic")),
        "sql": ("SQL", ()),
        "html": ("HTML", ("html5",)),
        "css": ("CSS", ("css3",)),
    },
    "Frontend": {
        "react": ("React", ("react.js", "reactjs")),
        "angular": ("Angular", ("angularjs", "angular.js")),
        "vue": ("Vue.js", ("vue.js", "vuejs")),
        "svelte": ("Svelte", ("sveltekit",)),
        "next.js": ("Next.js", ("nextjs", "next js")),
        "nuxt.js": ("Nuxt.js", ("nuxtjs", "nuxt")),
        "redux": ("Redux", ()),
        "jquery": ("jQuery", ()),
        "sass": ("Sass", ("scss",)),
        "less": ("Less", ()),
        "tailwind": ("Tailwind CSS", ("tailwindcss", "tailwind css")),
        "bootstrap": ("Bootstrap", ()),
        "material ui": ("Material UI", ("mui", "material-ui")),
        "webpack": ("Webpack", ()),
        "vite": ("Vite", ()),
        "babel": ("Babel", ()),
        "three.js": ("Three.js", ("threejs",)),
        "d3": ("D3.js", ("d3.js", "d3js")),
        "web components": ("Web Components", ()),
        "responsive design": ("Responsive design", ("responsive web design",)),
        "accessibility": ("Accessibility", ("a11y", "wcag")),
        "pwa": ("Progressive Web Apps", ("progressive web app", "progressive web apps")),
    },
    "Backend & Frameworks": {
        "node.js": ("Node.js", ("nodejs", "node js", "node")),
        "express": ("Express.js", ("express.js", "expressjs")),
        "django": ("Django", ()),
        "flask": ("Flask", ()),
        "fastapi": ("FastAPI", ("fast api",)),
        "spring": ("Spring", ("spring boot", "springboot", "spring framework", "spring mvc", "spring cloud")),
        "rails": ("Ruby on Rails", ("ruby on rails", "ror")),
        "laravel": ("Laravel", ()),
        ".net": (".NET", ("dotnet", "dot net", ".net core", "asp.net", "asp.net core")),
        "graphql": ("GraphQL", ()),
        "rest api": ("REST APIs", ("restful", "restful api", "restful apis", "rest apis", "restful services")),
        "grpc": ("gRPC", ()),
        "websocket": ("WebSockets", ("websockets", "web sockets")),
        "microservices": ("Microservices", ("micro services", "microservice")),
        "serverless": ("Serverless", ("aws lambda", "lambda functions", "cloud functions")),
        "oauth": ("OAuth", ("oauth2", "oauth 2.0")),
        "jwt": ("JWT", ("json web token", "json web tokens")),
        "message queues": ("Message queues", ("message queue", "rabbitmq", "activemq", "amqp", "sqs", "pub/sub", "pubsub")),
        "celery": ("Celery", ()),
        "api design": ("API design", ("api development", "api integration", "api integrations")),
        "streamlit": ("Streamlit", ()),
        "gradio": ("Gradio", ()),
    },
    "Mobile": {
        "android": ("Android", ("android development", "android sdk")),
        "ios": ("iOS", ("ios development",)),
        "react native": ("React Native", ()),
        "flutter": ("Flutter", ()),
        "swiftui": ("SwiftUI", ("swift ui",)),
        "jetpack compose": ("Jetpack Compose", ()),
        "xamarin": ("Xamarin", ()),
        "ionic": ("Ionic", ()),
        "mobile development": ("Mobile development", ("mobile app development", "mobile applications")),
    },
    "AI / ML": {
        "machine learning": ("Machine Learning", ("ml",)),
        "deep learning": ("Deep Learning", ("dl", "neural networks", "neural network")),
        "nlp": ("NLP", ("natural language processing",)),
        "computer vision": ("Computer Vision", ("cv", "image processing", "opencv")),
        "tensorflow": ("TensorFlow", ("tensor flow",)),
        "pytorch": ("PyTorch", ("torch",)),
        "keras": ("Keras", ()),
        "scikit-learn": ("scikit-learn", ("scikit learn", "sklearn", "sci-kit learn")),
        "xgboost": ("XGBoost", ()),
        "lightgbm": ("LightGBM", ()),
        "transformers": ("Transformers", ("transformer models", "transformer")),
        "huggingface": ("Hugging Face", ("hugging face",)),
        "langchain": ("LangChain", ()),
        "llamaindex": ("LlamaIndex", ("llama index", "llama-index")),
        "openai": ("OpenAI API", ("openai api", "gpt-4", "gpt-3", "chatgpt api")),
        "anthropic": ("Anthropic API", ("claude api",)),
        "llm": ("LLMs", ("large language model", "large language models", "llms")),
        "generative ai": ("Generative AI", ("genai", "gen ai")),
        "rag": ("RAG", ("retrieval augmented generation", "retrieval-augmented generation")),
        "prompt engineering": ("Prompt engineering", ()),
        "fine-tuning": ("Fine-tuning", ("finetuning", "fine tuning", "model fine-tuning")),
        "bert": ("BERT", ()),
        "gpt": ("GPT", ()),
        "stable diffusion": ("Stable Diffusion", ()),
        "reinforcement learning": ("Reinforcement Learning", ("rl",)),
        "recommendation systems": ("Recommendation systems", ("recommender systems", "recommendation engine")),
        "mlops": ("MLOps", ("ml ops",)),
        "mlflow": ("MLflow", ()),
        "kubeflow": ("Kubeflow", ()),
        "model deployment": ("Model deployment", ("model serving",)),
        "vector databases": ("Vector databases", ("vector database", "vector db", "pinecone", "weaviate", "milvus", "faiss", "chromadb", "chroma db")),
        "speech recognition": ("Speech recognition", ("asr", "speech-to-text", "speech to text")),
        "anomaly detection": ("Anomaly detection", ()),
        "time series": ("Time series", ("time series analysis", "time-series", "forecasting")),
        "feature engineering": ("Feature engineering", ()),
        "classification": ("Classification", ()),
        "regression": ("Regression", ()),
        "clustering": ("Clustering", ()),
    },
    "Data Engineering & Analytics": {
        "data science": ("Data Science", ()),
        "data analysis": ("Data analysis", ("data analytics",)),
        "data engineering": ("Data engineering", ()),
        "data visualization": ("Data visualization", ("data viz",)),
        "data modeling": ("Data modeling", ("data modelling",)),
        "statistics": ("Statistics", ("statistical analysis", "statistical modeling")),
        "a/b testing": ("A/B testing", ("ab testing", "a b testing", "split testing")),
        "hypothesis testing": ("Hypothesis testing", ()),
        "pandas": ("pandas", ()),
        "numpy": ("NumPy", ()),
        "scipy": ("SciPy", ()),
        "matplotlib": ("Matplotlib", ()),
        "seaborn": ("Seaborn", ()),
        "plotly": ("Plotly", ()),
        "tableau": ("Tableau", ()),
        "power bi": ("Power BI", ("powerbi",)),
        "looker": ("Looker", ()),
        "excel": ("Excel", ("microsoft excel", "ms excel")),
        "google analytics": ("Google Analytics", ()),
        "dbt": ("dbt", ()),
        "airflow": ("Airflow", ("apache airflow",)),
        "spark": ("Spark", ("apache spark", "pyspark")),
        "hadoop": ("Hadoop", ()),
        "kafka": ("Kafka", ("apache kafka",)),
        "flink": ("Flink", ("apache flink",)),
        "etl": ("ETL", ("elt", "etl pipelines", "etl pipeline", "data pipelines", "data pipeline")),
        "data warehouse": ("Data warehousing", ("data warehousing", "data warehouses")),
        "snowflake": ("Snowflake", ()),
        "redshift": ("Redshift", ("amazon redshift",)),
        "bigquery": ("BigQuery", ("big query",)),
        "databricks": ("Databricks", ()),
        "data governance": ("Data governance", ("data quality",)),
    },
    "Cloud & DevOps": {
        "aws": ("AWS", ("amazon web services",)),
        "azure": ("Azure", ("microsoft azure",)),
        "gcp": ("GCP", ("google cloud", "google cloud platform")),
        "docker": ("Docker", ("containerization", "containers")),
        "kubernetes": ("Kubernetes", ("k8s",)),
        "helm": ("Helm", ()),
        "terraform": ("Terraform", ()),
        "ansible": ("Ansible", ()),
        "pulumi": ("Pulumi", ()),
        "cloudformation": ("CloudFormation", ("cloud formation",)),
        "jenkins": ("Jenkins", ()),
        "github actions": ("GitHub Actions", ()),
        "gitlab ci": ("GitLab CI", ("gitlab ci/cd", "gitlab-ci")),
        "circleci": ("CircleCI", ("circle ci",)),
        "argocd": ("Argo CD", ("argo cd",)),
        "ci/cd": ("CI/CD", ("cicd", "continuous integration", "continuous delivery", "continuous deployment")),
        "devops": ("DevOps", ()),
        "sre": ("SRE", ("site reliability", "site reliability engineering")),
        "infrastructure as code": ("Infrastructure as Code", ("iac",)),
        "linux": ("Linux", ()),
        "unix": ("Unix", ()),
        "nginx": ("Nginx", ()),
        "apache": ("Apache", ("apache http",)),
        "monitoring": ("Monitoring & observability", ("observability", "prometheus", "grafana", "datadog", "new relic", "splunk")),
        "load balancing": ("Load balancing", ("load balancer", "load balancers")),
        "vercel": ("Vercel", ()),
        "netlify": ("Netlify", ()),
        "heroku": ("Heroku", ()),
        "ec2": ("EC2", ()),
        "s3": ("S3", ()),
        "cost optimization": ("Cloud cost optimization", ("finops",)),
    },
    "Databases": {
        "mysql": ("MySQL", ()),
        "postgresql": ("PostgreSQL", ("postgres", "postgre sql")),
        "mongodb": ("MongoDB", ("mongo db", "mongo")),
        "redis": ("Redis", ()),
        "elasticsearch": ("Elasticsearch", ("elastic search", "opensearch")),
        "cassandra": ("Cassandra", ()),
        "dynamodb": ("DynamoDB", ("dynamo db",)),
        "sqlite": ("SQLite", ()),
        "oracle": ("Oracle", ("oracle db", "oracle database")),
        "sql server": ("SQL Server", ("mssql", "microsoft sql server")),
        "mariadb": ("MariaDB", ()),
        "firebase": ("Firebase", ("firestore",)),
        "supabase": ("Supabase", ()),
        "neo4j": ("Neo4j", ()),
        "clickhouse": ("ClickHouse", ()),
        "influxdb": ("InfluxDB", ()),
        "database design": ("Database design", ("schema design", "database optimization", "query optimization")),
        "nosql": ("NoSQL", ()),
    },
    "Testing & QA": {
        "unit testing": ("Unit testing", ("unit tests",)),
        "integration testing": ("Integration testing", ("integration tests",)),
        "test automation": ("Test automation", ("automated testing", "automation testing")),
        "tdd": ("TDD", ("test driven development", "test-driven development")),
        "pytest": ("pytest", ()),
        "jest": ("Jest", ()),
        "selenium": ("Selenium", ()),
        "cypress": ("Cypress", ()),
        "playwright": ("Playwright", ()),
        "junit": ("JUnit", ()),
        "postman": ("Postman", ()),
        "load testing": ("Load testing", ("performance testing", "jmeter", "locust")),
        "qa": ("QA", ("quality assurance",)),
    },
    "Security": {
        "cybersecurity": ("Cybersecurity", ("cyber security", "information security", "infosec")),
        "penetration testing": ("Penetration testing", ("pen testing", "pentesting", "ethical hacking")),
        "application security": ("Application security", ("appsec", "secure coding")),
        "network security": ("Network security", ()),
        "cryptography": ("Cryptography", ("encryption",)),
        "iam": ("Identity & access management", ("identity and access management", "access control")),
        "siem": ("SIEM", ()),
        "vulnerability assessment": ("Vulnerability assessment", ("vulnerability management", "vulnerability scanning")),
        "owasp": ("OWASP", ()),
        "soc 2": ("SOC 2", ("soc2",)),
        "gdpr": ("GDPR", ()),
        "hipaa": ("HIPAA", ()),
        "pci dss": ("PCI DSS", ("pci-dss",)),
        "zero trust": ("Zero Trust", ()),
        "networking": ("Networking", ("tcp/ip", "dns", "vpn", "firewall", "firewalls")),
    },
    "Tools & Practices": {
        "git": ("Git", ("version control",)),
        "github": ("GitHub", ()),
        "gitlab": ("GitLab", ()),
        "bitbucket": ("Bitbucket", ()),
        "jira": ("Jira", ()),
        "confluence": ("Confluence", ()),
        "agile": ("Agile", ("agile methodologies", "agile development", "agile methodology")),
        "scrum": ("Scrum", ()),
        "kanban": ("Kanban", ()),
        "code review": ("Code review", ("code reviews", "peer review")),
        "design patterns": ("Design patterns", ()),
        "system design": ("System design", ("distributed systems", "software architecture", "systems design")),
        "oop": ("OOP", ("object oriented programming", "object-oriented programming", "object oriented design")),
        "functional programming": ("Functional programming", ()),
        "data structures": ("Data structures & algorithms", ("algorithms", "data structures and algorithms", "dsa")),
        "debugging": ("Debugging", ("troubleshooting",)),
        "technical documentation": ("Technical documentation", ("documentation",)),
        "performance optimization": ("Performance optimization", ("performance tuning",)),
        "vim": ("Vim", ()),
        "vs code": ("VS Code", ("vscode", "visual studio code")),
        "game development": ("Game development", ("unity", "unreal engine", "unreal", "godot")),
        "embedded systems": ("Embedded systems", ("embedded software", "firmware", "arduino", "raspberry pi", "rtos")),
        "iot": ("IoT", ("internet of things",)),
        "blockchain": ("Blockchain", ("web3", "smart contracts", "smart contract", "ethereum")),
        "salesforce": ("Salesforce", ()),
        "sap": ("SAP", ()),
        "servicenow": ("ServiceNow", ()),
        "sharepoint": ("SharePoint", ()),
    },
    "Design & UX": {
        "ui/ux": ("UI/UX", ("ui/ux design", "ux design", "ui design", "user experience", "user interface design")),
        "figma": ("Figma", ()),
        "sketch": ("Sketch", ()),
        "adobe xd": ("Adobe XD", ()),
        "photoshop": ("Photoshop", ("adobe photoshop",)),
        "illustrator": ("Illustrator", ("adobe illustrator",)),
        "wireframing": ("Wireframing", ("wireframes",)),
        "prototyping": ("Prototyping", ()),
        "user research": ("User research", ("usability testing",)),
        "design systems": ("Design systems", ("design system",)),
    },
    "Business & Product": {
        "product management": ("Product management", ()),
        "project management": ("Project management", ()),
        "program management": ("Program management", ()),
        "business analysis": ("Business analysis", ("business analyst", "requirements gathering")),
        "product strategy": ("Product strategy", ("product roadmap", "roadmap planning")),
        "market research": ("Market research", ("competitive analysis",)),
        "seo": ("SEO", ("search engine optimization",)),
        "sem": ("SEM", ("search engine marketing", "google ads", "ppc")),
        "digital marketing": ("Digital marketing", ("content marketing", "email marketing", "social media marketing")),
        "crm": ("CRM", ("hubspot", "customer relationship management")),
        "financial modeling": ("Financial modeling", ("financial analysis",)),
        "supply chain": ("Supply chain", ("supply chain management", "logistics")),
        "operations management": ("Operations management", ()),
        "vendor management": ("Vendor management", ("procurement",)),
        "risk management": ("Risk management", ()),
        "compliance": ("Compliance", ("regulatory compliance",)),
        "sales": ("Sales", ("business development", "b2b sales", "account management")),
        "customer success": ("Customer success", ("customer support", "customer service")),
        "okrs": ("OKRs", ("okr", "kpis", "kpi")),
    },
    "Certifications": {
        "pmp": ("PMP", ("project management professional",)),
        "aws certified": ("AWS Certified", ("aws certification", "aws solutions architect", "aws certified solutions architect")),
        "azure certified": ("Azure Certified", ("azure certification", "az-900", "az-104", "az-204")),
        "gcp certified": ("GCP Certified", ("google cloud certified", "gcp certification")),
        "cka": ("CKA", ("certified kubernetes administrator",)),
        "cissp": ("CISSP", ()),
        "ceh": ("CEH", ("certified ethical hacker",)),
        "comptia": ("CompTIA", ("comptia security+", "security+", "comptia a+", "comptia network+")),
        "scrum master": ("Scrum Master", ("csm", "certified scrum master", "psm")),
        "six sigma": ("Six Sigma", ("lean six sigma",)),
        "itil": ("ITIL", ()),
        "cfa": ("CFA", ("chartered financial analyst",)),
        "cpa": ("CPA", ("certified public accountant",)),
    },
    "Soft Skills": {
        "leadership": ("Leadership", ("team leadership", "team lead")),
        "communication": ("Communication", ("communication skills", "verbal communication", "written communication")),
        "teamwork": ("Teamwork", ("team player", "collaboration", "collaborative")),
        "problem solving": ("Problem solving", ("problem-solving",)),
        "critical thinking": ("Critical thinking", ()),
        "analytical thinking": ("Analytical thinking", ("analytical skills",)),
        "time management": ("Time management", ()),
        "adaptability": ("Adaptability", ("flexibility",)),
        "mentoring": ("Mentoring", ("mentorship", "coaching")),
        "stakeholder management": ("Stakeholder management", ("stakeholder communication",)),
        "strategic thinking": ("Strategic thinking", ("strategic planning",)),
        "cross-functional": ("Cross-functional collaboration", ("cross functional", "cross-functional teams")),
        "presentation": ("Presentation skills", ("public speaking", "presentations")),
        "negotiation": ("Negotiation", ()),
        "attention to detail": ("Attention to detail", ("detail-oriented", "detail oriented")),
    },
}

# Soft/generic skills: still detected and matched, but excluded from
# "missing skill" gap lists and JD requirement sets — every candidate
# claims them, so they only add noise to screening decisions.
SOFT_GENERIC: frozenset[str] = frozenset(_TAXONOMY_SOURCE["Soft Skills"].keys())

# ── Derived lookup tables ────────────────────────────────────────────
DISPLAY: dict[str, str] = {}
CATEGORY: dict[str, str] = {}
ALIASES: dict[str, tuple[str, ...]] = {}
ALIAS_TO_CANON: dict[str, str] = {}
CATEGORY_ORDER: tuple[str, ...] = tuple(_TAXONOMY_SOURCE.keys())

for _cat, _skills in _TAXONOMY_SOURCE.items():
    for _canon, (_display, _aliases) in _skills.items():
        DISPLAY[_canon] = _display
        CATEGORY[_canon] = _cat
        ALIASES[_canon] = _aliases
        ALIAS_TO_CANON[_canon] = _canon
        ALIAS_TO_CANON[_display.lower()] = _canon
        for _a in _aliases:
            ALIAS_TO_CANON[_a] = _canon

ALL_CANONICALS: frozenset[str] = frozenset(DISPLAY.keys())


def canonicalize(term: str) -> str | None:
    """Resolve any alias/display form to its canonical skill, or None."""
    return ALIAS_TO_CANON.get(term.lower().strip())


def display_name(canon: str) -> str:
    return DISPLAY.get(canon, canon)


def category_of(canon: str) -> str:
    return CATEGORY.get(canon, "Other")
